-- BORRACHOS LEAGUE 26/27 - RESET SPORTIVO CONTROLLATO
-- Generato 06/10/2026
-- Fonti: listone corrente dati.json (599 Serie A) + export Rose Leghe Fantacalcio (250 con prezzi) + crediti reali Gestione Crediti.
-- NON modifica password, login, deleghe, admin o funzioni RPC.

BEGIN;

DO $$
DECLARE v_missing text;
BEGIN
  SELECT string_agg(x.nome, ', ') INTO v_missing
  FROM (VALUES
    ('Tricchetracht Frankfurt'),
    ('Sesto Asensio'),
    ('Pesciculini'),
    ('Partizan Degrado'),
    ('AC Asparaghese'),
    ('San Gria'),
    ('Atl. Improvvisato'),
    ('Shark'),
    ('AS Pipperia'),
    ('FC Internazioanale')
  ) AS x(nome)
  WHERE NOT EXISTS (SELECT 1 FROM public.squadre s WHERE s.nome=x.nome);
  IF v_missing IS NOT NULL THEN RAISE EXCEPTION 'Squadre mancanti nel DB: %', v_missing; END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.backup_players_20261006 AS TABLE public.players;
CREATE TABLE IF NOT EXISTS public.backup_squadre_20261006 AS TABLE public.squadre;
CREATE TABLE IF NOT EXISTS public.backup_auction_movements_20261006 AS TABLE public.auction_movements;

UPDATE public.auction_state SET started_at=NULL, active_player_id=NULL, active_called_at=NULL, last_bid_at=NULL, paused_preauction=false WHERE id=1;
DELETE FROM public.bids;
DELETE FROM public.snapshot_players;
DELETE FROM public.snapshot_squadre;
DELETE FROM public.auction_movements;
DELETE FROM public.players;

INSERT INTO public.players (nome, ruolo, stato, vincitore, prezzo_finale, in_serie_a) VALUES
  ('Malen', 'ATT', 'pending', NULL, NULL, true),
  ('Moreira', 'CENTRO', 'pending', NULL, NULL, true),
  ('Gatti', 'DIF', 'pending', NULL, NULL, true),
  ('Varela G.', 'ATT', 'pending', NULL, NULL, true),
  ('Odenthal', 'DIF', 'pending', NULL, NULL, true),
  ('Zeballos', 'ATT', 'pending', NULL, NULL, true),
  ('Martinez L.', 'ATT', 'pending', NULL, NULL, true),
  ('Zhegrova', 'CENTRO', 'pending', NULL, NULL, true),
  ('Kvernadze', 'ATT', 'pending', NULL, NULL, true),
  ('Pulisic', 'CENTRO', 'pending', NULL, NULL, true),
  ('Raimondo', 'ATT', 'pending', NULL, NULL, true),
  ('Adzic', 'CENTRO', 'pending', NULL, NULL, true),
  ('Thuram', 'ATT', 'pending', NULL, NULL, true),
  ('Calhanoglu', 'CENTRO', 'pending', NULL, NULL, true),
  ('Frattesi', 'CENTRO', 'pending', NULL, NULL, true),
  ('Adams C.', 'ATT', 'pending', NULL, NULL, true),
  ('Maldini', 'ATT', 'pending', NULL, NULL, true),
  ('Esposito F.P.', 'ATT', 'pending', NULL, NULL, true),
  ('Carlos Augusto', 'DIF', 'pending', NULL, NULL, true),
  ('Dybala', 'ATT', 'pending', NULL, NULL, true),
  ('Kaiki', 'DIF', 'pending', NULL, NULL, true),
  ('Noslin', 'ATT', 'pending', NULL, NULL, true),
  ('Rabiot', 'CENTRO', 'pending', NULL, NULL, true),
  ('Kulenovic', 'ATT', 'pending', NULL, NULL, true),
  ('Mastantuono', 'CENTRO', 'pending', NULL, NULL, true),
  ('Pisilli', 'CENTRO', 'pending', NULL, NULL, true),
  ('Cissè A.', 'CENTRO', 'pending', NULL, NULL, true),
  ('Diao', 'ATT', 'pending', NULL, NULL, true),
  ('Konè M.', 'CENTRO', 'pending', NULL, NULL, true),
  ('Soulè', 'ATT', 'pending', NULL, NULL, true),
  ('Esposito Se.', 'ATT', 'pending', NULL, NULL, true),
  ('Romero D.', 'ATT', 'pending', NULL, NULL, true),
  ('Osmajic', 'ATT', 'pending', NULL, NULL, true),
  ('Kamara H.', 'DIF', 'pending', NULL, NULL, true),
  ('Ekkelenkamp', 'CENTRO', 'pending', NULL, NULL, true),
  ('Vergara', 'CENTRO', 'pending', NULL, NULL, true),
  ('Robinson J.', 'ATT', 'pending', NULL, NULL, true),
  ('Tiago Gabriel', 'DIF', 'pending', NULL, NULL, true),
  ('Bisseck', 'DIF', 'pending', NULL, NULL, true),
  ('Bremer', 'DIF', 'pending', NULL, NULL, true),
  ('Coulibaly L.', 'CENTRO', 'pending', NULL, NULL, true),
  ('Gonzalez N.', 'CENTRO', 'pending', NULL, NULL, true),
  ('Calò', 'CENTRO', 'pending', NULL, NULL, true),
  ('Diouf', 'CENTRO', 'pending', NULL, NULL, true),
  ('Volpato', 'CENTRO', 'pending', NULL, NULL, true),
  ('Romano', 'CENTRO', 'pending', NULL, NULL, true),
  ('Baturina', 'CENTRO', 'pending', NULL, NULL, true),
  ('Paz N.', 'CENTRO', 'pending', NULL, NULL, true),
  ('Douvikas', 'ATT', 'pending', NULL, NULL, true),
  ('Gorter', 'CENTRO', 'pending', NULL, NULL, true),
  ('Zielinski', 'CENTRO', 'pending', NULL, NULL, true),
  ('Zaccagni', 'CENTRO', 'pending', NULL, NULL, true),
  ('Mangas', 'DIF', 'pending', NULL, NULL, true),
  ('Bonny', 'ATT', 'pending', NULL, NULL, true),
  ('Gilmour', 'CENTRO', 'pending', NULL, NULL, true),
  ('Hojlund', 'ATT', 'pending', NULL, NULL, true),
  ('Mina', 'DIF', 'pending', NULL, NULL, true),
  ('Ramon', 'DIF', 'pending', NULL, NULL, true),
  ('Barella', 'CENTRO', 'pending', NULL, NULL, true),
  ('Koopmeiners', 'CENTRO', 'pending', NULL, NULL, true),
  ('Conceicao', 'CENTRO', 'pending', NULL, NULL, true),
  ('Tavares N.', 'DIF', 'pending', NULL, NULL, true),
  ('De Bruyne', 'CENTRO', 'pending', NULL, NULL, true),
  ('Almqvist', 'CENTRO', 'pending', NULL, NULL, true),
  ('Hermoso', 'DIF', 'pending', NULL, NULL, true),
  ('Favasuli', 'DIF', 'pending', NULL, NULL, true),
  ('Mendy P.', 'ATT', 'pending', NULL, NULL, true),
  ('Mandragora', 'CENTRO', 'pending', NULL, NULL, true),
  ('Bracaglia', 'DIF', 'pending', NULL, NULL, true),
  ('Raspadori', 'ATT', 'pending', NULL, NULL, true),
  ('Jimenez A.', 'DIF', 'pending', NULL, NULL, true),
  ('Berardi', 'ATT', 'pending', NULL, NULL, true),
  ('Mora', 'CENTRO', 'pending', NULL, NULL, true),
  ('Dovbyk', 'ATT', 'pending', NULL, NULL, true),
  ('Doekhi', 'DIF', 'pending', NULL, NULL, true),
  ('Piotrowski', 'CENTRO', 'pending', NULL, NULL, true),
  ('Sagrado', 'DIF', 'pending', NULL, NULL, true),
  ('Bernardeschi', 'CENTRO', 'pending', NULL, NULL, true),
  ('Chukwueze', 'CENTRO', 'pending', NULL, NULL, true),
  ('Ramos G.', 'ATT', 'pending', NULL, NULL, true),
  ('Pellegrino M.', 'ATT', 'pending', NULL, NULL, true),
  ('Doig', 'DIF', 'pending', NULL, NULL, true),
  ('Hainaut', 'DIF', 'pending', NULL, NULL, true),
  ('Wesley', 'DIF', 'pending', NULL, NULL, true),
  ('Comuzzo', 'DIF', 'pending', NULL, NULL, true),
  ('Gueye', 'ATT', 'pending', NULL, NULL, true),
  ('Ederson D.S.', 'CENTRO', 'pending', NULL, NULL, true),
  ('Cancellieri', 'CENTRO', 'pending', NULL, NULL, true),
  ('Lobotka', 'CENTRO', 'pending', NULL, NULL, true),
  ('Bowie', 'ATT', 'pending', NULL, NULL, true),
  ('Schmid', 'CENTRO', 'pending', NULL, NULL, true),
  ('Bakola', 'CENTRO', 'pending', NULL, NULL, true),
  ('Davis K.', 'ATT', 'pending', NULL, NULL, true),
  ('Busio', 'CENTRO', 'pending', NULL, NULL, true),
  ('Adopo', 'CENTRO', 'pending', NULL, NULL, true),
  ('Mandas', 'POR', 'pending', NULL, NULL, true),
  ('De Roon', 'CENTRO', 'pending', NULL, NULL, true),
  ('Sulemana I.', 'CENTRO', 'pending', NULL, NULL, true),
  ('Gudmundsson A.', 'CENTRO', 'pending', NULL, NULL, true),
  ('Masini', 'CENTRO', 'pending', NULL, NULL, true),
  ('Locatelli', 'CENTRO', 'pending', NULL, NULL, true),
  ('Saelemaekers', 'CENTRO', 'pending', NULL, NULL, true),
  ('Colpani', 'CENTRO', 'pending', NULL, NULL, true),
  ('Rrahmani', 'DIF', 'pending', NULL, NULL, true),
  ('Palma', 'DIF', 'pending', NULL, NULL, true),
  ('Abankwah', 'DIF', 'pending', NULL, NULL, true),
  ('Samardzic', 'CENTRO', 'pending', NULL, NULL, true),
  ('Obert', 'DIF', 'pending', NULL, NULL, true),
  ('Winks', 'CENTRO', 'pending', NULL, NULL, true),
  ('Da Cunha', 'CENTRO', 'pending', NULL, NULL, true),
  ('Piccoli', 'ATT', 'pending', NULL, NULL, true),
  ('Oyono A.', 'DIF', 'pending', NULL, NULL, true),
  ('Gila', 'DIF', 'pending', NULL, NULL, true),
  ('Politano', 'CENTRO', 'pending', NULL, NULL, true),
  ('Mancini', 'DIF', 'pending', NULL, NULL, true),
  ('Matic', 'CENTRO', 'pending', NULL, NULL, true),
  ('Laurientè', 'ATT', 'pending', NULL, NULL, true),
  ('Karlstrom', 'CENTRO', 'pending', NULL, NULL, true),
  ('Cinquegrano', 'DIF', 'pending', NULL, NULL, true),
  ('Valle', 'DIF', 'pending', NULL, NULL, true),
  ('Molina N.', 'DIF', 'pending', NULL, NULL, true),
  ('Ghedjemis', 'ATT', 'pending', NULL, NULL, true),
  ('Elphege', 'ATT', 'pending', NULL, NULL, true),
  ('Balerdi', 'DIF', 'pending', NULL, NULL, true),
  ('Krstovic', 'ATT', 'pending', NULL, NULL, true),
  ('Scamacca', 'ATT', 'pending', NULL, NULL, true),
  ('Ferguson', 'CENTRO', 'pending', NULL, NULL, true),
  ('Rodriguez Ju.', 'DIF', 'pending', NULL, NULL, true),
  ('Dimarco', 'DIF', 'pending', NULL, NULL, true),
  ('Celik', 'DIF', 'pending', NULL, NULL, true),
  ('Pavlovic', 'DIF', 'pending', NULL, NULL, true),
  ('Cristante', 'CENTRO', 'pending', NULL, NULL, true),
  ('Lontani', 'ATT', 'pending', NULL, NULL, true),
  ('Leysen F.', 'DIF', 'pending', NULL, NULL, true),
  ('Miranda J.', 'DIF', 'pending', NULL, NULL, true),
  ('McKennie', 'CENTRO', 'pending', NULL, NULL, true),
  ('Rovella', 'CENTRO', 'pending', NULL, NULL, true),
  ('Dia', 'ATT', 'pending', NULL, NULL, true),
  ('Akinsanmiro', 'CENTRO', 'pending', NULL, NULL, true),
  ('Ilic', 'CENTRO', 'pending', NULL, NULL, true),
  ('Sutalo J.', 'DIF', 'pending', NULL, NULL, true),
  ('Lulli', 'DIF', 'pending', NULL, NULL, true),
  ('Zè Pedro', 'DIF', 'pending', NULL, NULL, true),
  ('Milla', 'CENTRO', 'pending', NULL, NULL, true),
  ('Perrone', 'CENTRO', 'pending', NULL, NULL, true),
  ('Calvani', 'DIF', 'pending', NULL, NULL, true),
  ('Musah', 'CENTRO', 'pending', NULL, NULL, true),
  ('Di Lorenzo', 'DIF', 'pending', NULL, NULL, true),
  ('Adams A.', 'ATT', 'pending', NULL, NULL, true),
  ('Couto', 'DIF', 'pending', NULL, NULL, true),
  ('Zappacosta', 'DIF', 'pending', NULL, NULL, true),
  ('Zalewski', 'CENTRO', 'pending', NULL, NULL, true),
  ('Helland', 'DIF', 'pending', NULL, NULL, true),
  ('Kofler', 'DIF', 'pending', NULL, NULL, true),
  ('Braganca', 'CENTRO', 'pending', NULL, NULL, true),
  ('Fazzini', 'CENTRO', 'pending', NULL, NULL, true),
  ('Kean', 'ATT', 'pending', NULL, NULL, true),
  ('Belahyane', 'CENTRO', 'pending', NULL, NULL, true),
  ('Castro S.', 'ATT', 'pending', NULL, NULL, true),
  ('Chalobah T.', 'DIF', 'pending', NULL, NULL, true),
  ('Deiola', 'CENTRO', 'pending', NULL, NULL, true),
  ('Monterisi', 'DIF', 'pending', NULL, NULL, true),
  ('Messias', 'CENTRO', 'pending', NULL, NULL, true),
  ('Kalulu', 'DIF', 'pending', NULL, NULL, true),
  ('Taylor K.', 'CENTRO', 'pending', NULL, NULL, true),
  ('Veiga D.', 'DIF', 'pending', NULL, NULL, true),
  ('De Winter', 'DIF', 'pending', NULL, NULL, true),
  ('Modric', 'CENTRO', 'pending', NULL, NULL, true),
  ('Birindelli', 'DIF', 'pending', NULL, NULL, true),
  ('De Silvestri', 'DIF', 'pending', NULL, NULL, true),
  ('Holm', 'DIF', 'pending', NULL, NULL, true),
  ('Alhassane', 'DIF', 'pending', NULL, NULL, true),
  ('Caprile', 'POR', 'pending', NULL, NULL, true),
  ('Zappa', 'DIF', 'pending', NULL, NULL, true),
  ('Borrelli', 'ATT', 'pending', NULL, NULL, true),
  ('Kempf', 'DIF', 'pending', NULL, NULL, true),
  ('Fadera', 'CENTRO', 'pending', NULL, NULL, true),
  ('Liberali', 'CENTRO', 'pending', NULL, NULL, true),
  ('Ndour', 'CENTRO', 'pending', NULL, NULL, true),
  ('Palmisani', 'POR', 'pending', NULL, NULL, true),
  ('Hasa', 'CENTRO', 'pending', NULL, NULL, true),
  ('Vasquez', 'DIF', 'pending', NULL, NULL, true),
  ('Meichtry', 'CENTRO', 'pending', NULL, NULL, true),
  ('Luis Henrique', 'CENTRO', 'pending', NULL, NULL, true),
  ('Sucic P.', 'CENTRO', 'pending', NULL, NULL, true),
  ('Provstgaard', 'DIF', 'pending', NULL, NULL, true),
  ('Lazzari', 'DIF', 'pending', NULL, NULL, true),
  ('Pedraza', 'DIF', 'pending', NULL, NULL, true),
  ('Gabbia', 'DIF', 'pending', NULL, NULL, true),
  ('Bartesaghi', 'DIF', 'pending', NULL, NULL, true),
  ('Jashari', 'CENTRO', 'pending', NULL, NULL, true),
  ('Mota', 'ATT', 'pending', NULL, NULL, true),
  ('Milinkovic-Savic V.', 'POR', 'pending', NULL, NULL, true),
  ('Santos A.', 'ATT', 'pending', NULL, NULL, true),
  ('Valenti', 'DIF', 'pending', NULL, NULL, true),
  ('Diallo O.', 'CENTRO', 'pending', NULL, NULL, true),
  ('Ghilardi', 'DIF', 'pending', NULL, NULL, true),
  ('Koulierakis', 'DIF', 'pending', NULL, NULL, true),
  ('N''Dicka', 'DIF', 'pending', NULL, NULL, true),
  ('El Aynaoui', 'CENTRO', 'pending', NULL, NULL, true),
  ('Idzes', 'DIF', 'pending', NULL, NULL, true),
  ('Thorstvedt', 'CENTRO', 'pending', NULL, NULL, true),
  ('Comert', 'DIF', 'pending', NULL, NULL, true),
  ('Ismajli', 'DIF', 'pending', NULL, NULL, true),
  ('Cacciamani', 'CENTRO', 'pending', NULL, NULL, true),
  ('Oristanio', 'CENTRO', 'pending', NULL, NULL, true),
  ('Aboukhlal', 'CENTRO', 'pending', NULL, NULL, true),
  ('Njie', 'CENTRO', 'pending', NULL, NULL, true),
  ('Solet', 'DIF', 'pending', NULL, NULL, true),
  ('Zanoli', 'DIF', 'pending', NULL, NULL, true),
  ('Zarraga', 'CENTRO', 'pending', NULL, NULL, true),
  ('Chakvetadze', 'CENTRO', 'pending', NULL, NULL, true),
  ('Unai Gomez', 'CENTRO', 'pending', NULL, NULL, true),
  ('Obrador', 'DIF', 'pending', NULL, NULL, true),
  ('Jones C.', 'CENTRO', 'pending', NULL, NULL, true),
  ('Birligea', 'ATT', 'pending', NULL, NULL, true),
  ('Bobcek', 'ATT', 'pending', NULL, NULL, true),
  ('Gagliardini', 'CENTRO', 'pending', NULL, NULL, true),
  ('Hutchinson', 'CENTRO', 'pending', NULL, NULL, true),
  ('Diego Carlos', 'DIF', 'pending', NULL, NULL, true),
  ('Sarr P.', 'CENTRO', 'pending', NULL, NULL, true),
  ('Sugawara', 'DIF', 'pending', NULL, NULL, true),
  ('Goncalves P.', 'CENTRO', 'pending', NULL, NULL, true),
  ('El Shaarawy', 'CENTRO', 'pending', NULL, NULL, true),
  ('Rodriguez R.', 'DIF', 'pending', NULL, NULL, true),
  ('Lovric', 'CENTRO', 'pending', NULL, NULL, true),
  ('Esteban', 'ATT', 'pending', NULL, NULL, true),
  ('Fagioli', 'CENTRO', 'pending', NULL, NULL, true),
  ('Cittadini', 'DIF', 'pending', NULL, NULL, true),
  ('Maleh', 'CENTRO', 'pending', NULL, NULL, true),
  ('Valeri', 'DIF', 'pending', NULL, NULL, true),
  ('Fitz-Jim', 'CENTRO', 'pending', NULL, NULL, true),
  ('Yeboah J.', 'ATT', 'pending', NULL, NULL, true),
  ('Gaetano', 'CENTRO', 'pending', NULL, NULL, true),
  ('Lucumì', 'DIF', 'pending', NULL, NULL, true),
  ('Dominguez B.', 'CENTRO', 'pending', NULL, NULL, true),
  ('Fatah', 'ATT', 'pending', NULL, NULL, true),
  ('Pasalic', 'CENTRO', 'pending', NULL, NULL, true),
  ('Caqueret', 'CENTRO', 'pending', NULL, NULL, true),
  ('Oulai', 'CENTRO', 'pending', NULL, NULL, true),
  ('Zerbin', 'CENTRO', 'pending', NULL, NULL, true),
  ('Stones', 'DIF', 'pending', NULL, NULL, true),
  ('Kelly L.', 'DIF', 'pending', NULL, NULL, true),
  ('Boga', 'ATT', 'pending', NULL, NULL, true),
  ('Ricci S.', 'CENTRO', 'pending', NULL, NULL, true),
  ('Neres', 'ATT', 'pending', NULL, NULL, true),
  ('Ordonez C.', 'CENTRO', 'pending', NULL, NULL, true),
  ('Bernabè', 'CENTRO', 'pending', NULL, NULL, true),
  ('Ilkhan', 'CENTRO', 'pending', NULL, NULL, true),
  ('Bertola', 'DIF', 'pending', NULL, NULL, true),
  ('Lauberbach', 'ATT', 'pending', NULL, NULL, true),
  ('Forson O.', 'CENTRO', 'pending', NULL, NULL, true),
  ('Theate', 'DIF', 'pending', NULL, NULL, true),
  ('Belghali', 'DIF', 'pending', NULL, NULL, true),
  ('Gnonto', 'ATT', 'pending', NULL, NULL, true),
  ('Heggem', 'DIF', 'pending', NULL, NULL, true),
  ('Frendrup', 'CENTRO', 'pending', NULL, NULL, true),
  ('Bastoni', 'DIF', 'pending', NULL, NULL, true),
  ('Douglas Luiz', 'CENTRO', 'pending', NULL, NULL, true),
  ('Floriani Mussolini', 'DIF', 'pending', NULL, NULL, true),
  ('Delprato', 'DIF', 'pending', NULL, NULL, true),
  ('Coco', 'DIF', 'pending', NULL, NULL, true),
  ('Ebosse', 'DIF', 'pending', NULL, NULL, true),
  ('Sow', 'CENTRO', 'pending', NULL, NULL, true),
  ('Fortini', 'DIF', 'pending', NULL, NULL, true),
  ('Moro N.', 'CENTRO', 'pending', NULL, NULL, true),
  ('Pobega', 'CENTRO', 'pending', NULL, NULL, true),
  ('Felici', 'CENTRO', 'pending', NULL, NULL, true),
  ('Joao Mario', 'DIF', 'pending', NULL, NULL, true),
  ('Norton-Cuffy', 'DIF', 'pending', NULL, NULL, true),
  ('Pavard', 'DIF', 'pending', NULL, NULL, true),
  ('Cambiaso', 'DIF', 'pending', NULL, NULL, true),
  ('Alajbegovic', 'CENTRO', 'pending', NULL, NULL, true),
  ('Gallo', 'DIF', 'pending', NULL, NULL, true),
  ('Cutrone', 'ATT', 'pending', NULL, NULL, true),
  ('Pinamonti', 'ATT', 'pending', NULL, NULL, true),
  ('Zaniolo', 'CENTRO', 'pending', NULL, NULL, true),
  ('Correia T.', 'DIF', 'pending', NULL, NULL, true),
  ('Haps', 'DIF', 'pending', NULL, NULL, true),
  ('Terzic', 'DIF', 'pending', NULL, NULL, true),
  ('Woltemade', 'ATT', 'pending', NULL, NULL, true),
  ('Patterson', 'DIF', 'pending', NULL, NULL, true),
  ('Fernandez T.', 'CENTRO', 'pending', NULL, NULL, true),
  ('Sierro', 'CENTRO', 'pending', NULL, NULL, true),
  ('Scalvini', 'DIF', 'pending', NULL, NULL, true),
  ('Baldanzi', 'CENTRO', 'pending', NULL, NULL, true),
  ('Ngom', 'CENTRO', 'pending', NULL, NULL, true),
  ('Lucca', 'ATT', 'pending', NULL, NULL, true),
  ('Svilar', 'POR', 'pending', NULL, NULL, true),
  ('Simeone', 'ATT', 'pending', NULL, NULL, true),
  ('Vojvoda', 'DIF', 'pending', NULL, NULL, true),
  ('Bernasconi', 'DIF', 'pending', NULL, NULL, true),
  ('Zortea', 'DIF', 'pending', NULL, NULL, true),
  ('Orsolini', 'CENTRO', 'pending', NULL, NULL, true),
  ('Rodriguez Je.', 'CENTRO', 'pending', NULL, NULL, true),
  ('Cichella', 'CENTRO', 'pending', NULL, NULL, true),
  ('Bakoune', 'DIF', 'pending', NULL, NULL, true),
  ('Britschgi', 'DIF', 'pending', NULL, NULL, true),
  ('Rrahmani Al.', 'ATT', 'pending', NULL, NULL, true),
  ('Kevin Carlos', 'ATT', 'pending', NULL, NULL, true),
  ('Beto', 'ATT', 'pending', NULL, NULL, true),
  ('Kolasinac', 'DIF', 'pending', NULL, NULL, true),
  ('Bellanova', 'DIF', 'pending', NULL, NULL, true),
  ('Valdepenas', 'DIF', 'pending', NULL, NULL, true),
  ('Viery', 'DIF', 'pending', NULL, NULL, true),
  ('Fini', 'CENTRO', 'pending', NULL, NULL, true),
  ('Amorim', 'CENTRO', 'pending', NULL, NULL, true),
  ('Estupinan', 'DIF', 'pending', NULL, NULL, true),
  ('Spinazzola', 'DIF', 'pending', NULL, NULL, true),
  ('Lang', 'ATT', 'pending', NULL, NULL, true),
  ('Dragusin', 'DIF', 'pending', NULL, NULL, true),
  ('Akanji', 'DIF', 'pending', NULL, NULL, true),
  ('Kolo Muani', 'ATT', 'pending', NULL, NULL, true),
  ('Pierotti', 'CENTRO', 'pending', NULL, NULL, true),
  ('Lucchesi', 'DIF', 'pending', NULL, NULL, true),
  ('Keita M.', 'CENTRO', 'pending', NULL, NULL, true),
  ('Perez K.', 'CENTRO', 'pending', NULL, NULL, true),
  ('De Ketelaere', 'ATT', 'pending', NULL, NULL, true),
  ('Amondarain', 'CENTRO', 'pending', NULL, NULL, true),
  ('Rowe', 'CENTRO', 'pending', NULL, NULL, true),
  ('Cambiaghi', 'CENTRO', 'pending', NULL, NULL, true),
  ('Tornqvist', 'POR', 'pending', NULL, NULL, true),
  ('Smolcic I.', 'DIF', 'pending', NULL, NULL, true),
  ('Fabbian', 'CENTRO', 'pending', NULL, NULL, true),
  ('Puczka', 'DIF', 'pending', NULL, NULL, true),
  ('Vitinha O.', 'ATT', 'pending', NULL, NULL, true),
  ('Colombo', 'ATT', 'pending', NULL, NULL, true),
  ('Mkhitaryan', 'CENTRO', 'pending', NULL, NULL, true),
  ('Yildiz', 'ATT', 'pending', NULL, NULL, true),
  ('David', 'ATT', 'pending', NULL, NULL, true),
  ('Marusic', 'DIF', 'pending', NULL, NULL, true),
  ('Dele-Bashiru', 'CENTRO', 'pending', NULL, NULL, true),
  ('Isaksen', 'CENTRO', 'pending', NULL, NULL, true),
  ('Ndaba', 'DIF', 'pending', NULL, NULL, true),
  ('Kaba', 'CENTRO', 'pending', NULL, NULL, true),
  ('Delli Carri', 'DIF', 'pending', NULL, NULL, true),
  ('McTominay', 'CENTRO', 'pending', NULL, NULL, true),
  ('Ndiaye', 'DIF', 'pending', NULL, NULL, true),
  ('Troilo', 'DIF', 'pending', NULL, NULL, true),
  ('Cremaschi', 'CENTRO', 'pending', NULL, NULL, true),
  ('Frigan', 'ATT', 'pending', NULL, NULL, true),
  ('Rensch', 'DIF', 'pending', NULL, NULL, true),
  ('Lipani', 'CENTRO', 'pending', NULL, NULL, true),
  ('Pedersen', 'DIF', 'pending', NULL, NULL, true),
  ('Miller L.', 'CENTRO', 'pending', NULL, NULL, true),
  ('Bayo V.', 'ATT', 'pending', NULL, NULL, true),
  ('Bella-Kotchap', 'DIF', 'pending', NULL, NULL, true),
  ('Basic', 'CENTRO', 'pending', NULL, NULL, true),
  ('Helgason', 'CENTRO', 'pending', NULL, NULL, true),
  ('Tourè E.', 'ATT', 'pending', NULL, NULL, true),
  ('Vicario', 'POR', 'pending', NULL, NULL, true),
  ('Foe Ondoa', 'CENTRO', 'pending', NULL, NULL, true),
  ('Badiashile', 'DIF', 'pending', NULL, NULL, true),
  ('Kessiè', 'CENTRO', 'pending', NULL, NULL, true),
  ('Juan Jesus', 'DIF', 'pending', NULL, NULL, true),
  ('Caleta-Car', 'DIF', 'pending', NULL, NULL, true),
  ('Atta', 'CENTRO', 'pending', NULL, NULL, true),
  ('Siebert', 'DIF', 'pending', NULL, NULL, true),
  ('Stulic', 'ATT', 'pending', NULL, NULL, true),
  ('Maignan', 'POR', 'pending', NULL, NULL, true),
  ('Loftus-Cheek', 'CENTRO', 'pending', NULL, NULL, true),
  ('Carboni A.', 'DIF', 'pending', NULL, NULL, true),
  ('Marin R.', 'DIF', 'pending', NULL, NULL, true),
  ('Kossounou', 'DIF', 'pending', NULL, NULL, true),
  ('N''Dri', 'ATT', 'pending', NULL, NULL, true),
  ('Folorunsho', 'CENTRO', 'pending', NULL, NULL, true),
  ('Gineitis', 'CENTRO', 'pending', NULL, NULL, true),
  ('Ranieri L.', 'DIF', 'pending', NULL, NULL, true),
  ('Brescianini', 'CENTRO', 'pending', NULL, NULL, true),
  ('Kabasele', 'DIF', 'pending', NULL, NULL, true),
  ('Monteiro J.', 'CENTRO', 'pending', NULL, NULL, true),
  ('Ehizibue', 'DIF', 'pending', NULL, NULL, true),
  ('Ostigard', 'DIF', 'pending', NULL, NULL, true),
  ('Ellertsson', 'CENTRO', 'pending', NULL, NULL, true),
  ('Kouadio', 'DIF', 'pending', NULL, NULL, true),
  ('Vlasic', 'CENTRO', 'pending', NULL, NULL, true),
  ('Olivera', 'DIF', 'pending', NULL, NULL, true),
  ('Franjic', 'DIF', 'pending', NULL, NULL, true),
  ('Elmas', 'CENTRO', 'pending', NULL, NULL, true),
  ('Drobnic', 'DIF', 'pending', NULL, NULL, true),
  ('Carnesecchi', 'POR', 'pending', NULL, NULL, true),
  ('Odgaard', 'CENTRO', 'pending', NULL, NULL, true),
  ('Zambo Anguissa', 'CENTRO', 'pending', NULL, NULL, true),
  ('Gaspar K.', 'DIF', 'pending', NULL, NULL, true),
  ('Sohm', 'CENTRO', 'pending', NULL, NULL, true),
  ('Pessina Mas.', 'POR', 'pending', NULL, NULL, true),
  ('El Azzouzi O.', 'CENTRO', 'pending', NULL, NULL, true),
  ('Pongracic', 'DIF', 'pending', NULL, NULL, true),
  ('Dodò', 'DIF', 'pending', NULL, NULL, true),
  ('Marcandalli', 'DIF', 'pending', NULL, NULL, true),
  ('Otoa', 'DIF', 'pending', NULL, NULL, true),
  ('Geubbels', 'ATT', 'pending', NULL, NULL, true),
  ('Colombo L.', 'CENTRO', 'pending', NULL, NULL, true),
  ('Corvi', 'POR', 'pending', NULL, NULL, true),
  ('Casadei', 'CENTRO', 'pending', NULL, NULL, true),
  ('Kristensen T.', 'DIF', 'pending', NULL, NULL, true),
  ('Moreno M.', 'DIF', 'pending', NULL, NULL, true),
  ('Dagasso', 'CENTRO', 'pending', NULL, NULL, true),
  ('Mout', 'CENTRO', 'pending', NULL, NULL, true),
  ('Sanchez Ro.', 'POR', 'pending', NULL, NULL, true),
  ('Libra', 'CENTRO', 'pending', NULL, NULL, true),
  ('Schingtienne', 'DIF', 'pending', NULL, NULL, true),
  ('Butez', 'POR', 'pending', NULL, NULL, true),
  ('Meret', 'POR', 'pending', NULL, NULL, true),
  ('Sabelli', 'DIF', 'pending', NULL, NULL, true),
  ('Martinez Jo.', 'POR', 'pending', NULL, NULL, true),
  ('Okoye', 'POR', 'pending', NULL, NULL, true),
  ('Perri', 'POR', 'pending', NULL, NULL, true),
  ('Skorupski', 'POR', 'pending', NULL, NULL, true),
  ('Mascardi', 'POR', 'pending', NULL, NULL, true),
  ('Falcone', 'POR', 'pending', NULL, NULL, true),
  ('Muric', 'POR', 'pending', NULL, NULL, true),
  ('Halhal', 'DIF', 'pending', NULL, NULL, true),
  ('Bijlow', 'POR', 'pending', NULL, NULL, true),
  ('Stankovic F.', 'POR', 'pending', NULL, NULL, true),
  ('De Gea', 'POR', 'pending', NULL, NULL, true),
  ('Thiam', 'POR', 'pending', NULL, NULL, true),
  ('Pizzignacco', 'POR', 'pending', NULL, NULL, true),
  ('Rossi F.', 'POR', 'pending', NULL, NULL, true),
  ('Sportiello', 'POR', 'pending', NULL, NULL, true),
  ('Djimsiti', 'DIF', 'pending', NULL, NULL, true),
  ('Hien', 'DIF', 'pending', NULL, NULL, true),
  ('Ahanor', 'DIF', 'pending', NULL, NULL, true),
  ('Sulemana K.', 'ATT', 'pending', NULL, NULL, true),
  ('Happonen', 'POR', 'pending', NULL, NULL, true),
  ('Casale', 'DIF', 'pending', NULL, NULL, true),
  ('Vitik', 'DIF', 'pending', NULL, NULL, true),
  ('Dallinga', 'ATT', 'pending', NULL, NULL, true),
  ('Ciocci', 'POR', 'pending', NULL, NULL, true),
  ('Sherri', 'POR', 'pending', NULL, NULL, true),
  ('Raterink', 'DIF', 'pending', NULL, NULL, true),
  ('Idrissi R.', 'DIF', 'pending', NULL, NULL, true),
  ('Liteta', 'CENTRO', 'pending', NULL, NULL, true),
  ('Prati', 'CENTRO', 'pending', NULL, NULL, true),
  ('Albarracin', 'ATT', 'pending', NULL, NULL, true),
  ('Mutandwa', 'ATT', 'pending', NULL, NULL, true),
  ('Trepy', 'ATT', 'pending', NULL, NULL, true),
  ('Vigorito', 'POR', 'pending', NULL, NULL, true),
  ('Goldaniga', 'DIF', 'pending', NULL, NULL, true),
  ('Cuenca A.', 'DIF', 'pending', NULL, NULL, true),
  ('Van Der Brempt', 'DIF', 'pending', NULL, NULL, true),
  ('Lahdo', 'CENTRO', 'pending', NULL, NULL, true),
  ('Addai', 'CENTRO', 'pending', NULL, NULL, true),
  ('Kuhn', 'ATT', 'pending', NULL, NULL, true),
  ('Azon', 'ATT', 'pending', NULL, NULL, true),
  ('Morata', 'ATT', 'pending', NULL, NULL, true),
  ('Christensen O.', 'POR', 'pending', NULL, NULL, true),
  ('Lezzerini', 'POR', 'pending', NULL, NULL, true),
  ('Parisi', 'DIF', 'pending', NULL, NULL, true),
  ('Desplanches', 'POR', 'pending', NULL, NULL, true),
  ('Lolic', 'POR', 'pending', NULL, NULL, true),
  ('Akpoguma', 'DIF', 'pending', NULL, NULL, true),
  ('Amey', 'DIF', 'pending', NULL, NULL, true),
  ('Gelli J.', 'DIF', 'pending', NULL, NULL, true),
  ('Oyono J.', 'DIF', 'pending', NULL, NULL, true),
  ('Corrado', 'DIF', 'pending', NULL, NULL, true),
  ('El Azzouzi A.', 'CENTRO', 'pending', NULL, NULL, true),
  ('Kone B.', 'CENTRO', 'pending', NULL, NULL, true),
  ('Koutsoupias', 'CENTRO', 'pending', NULL, NULL, true),
  ('Gelli F.', 'CENTRO', 'pending', NULL, NULL, true),
  ('Sommariva', 'POR', 'pending', NULL, NULL, true),
  ('Stolz', 'POR', 'pending', NULL, NULL, true),
  ('Vogliacco', 'DIF', 'pending', NULL, NULL, true),
  ('Matturro', 'DIF', 'pending', NULL, NULL, true),
  ('Martin', 'DIF', 'pending', NULL, NULL, true),
  ('Mitaj', 'DIF', 'pending', NULL, NULL, true),
  ('Venturino', 'CENTRO', 'pending', NULL, NULL, true),
  ('Traorè Hj.', 'CENTRO', 'pending', NULL, NULL, true),
  ('Havel', 'ATT', 'pending', NULL, NULL, true),
  ('Di Gennaro', 'POR', 'pending', NULL, NULL, true),
  ('Provedel', 'POR', 'pending', NULL, NULL, true),
  ('Stankovic A.', 'CENTRO', 'pending', NULL, NULL, true),
  ('Di Gregorio', 'POR', 'pending', NULL, NULL, true),
  ('Perin', 'POR', 'pending', NULL, NULL, true),
  ('Pinsoglio', 'POR', 'pending', NULL, NULL, true),
  ('Rugani', 'DIF', 'pending', NULL, NULL, true),
  ('Cabal', 'DIF', 'pending', NULL, NULL, true),
  ('Thuram K.', 'CENTRO', 'pending', NULL, NULL, true),
  ('Miretti', 'CENTRO', 'pending', NULL, NULL, true),
  ('Ekhator', 'ATT', 'pending', NULL, NULL, true),
  ('Motta', 'POR', 'pending', NULL, NULL, true),
  ('Renzetti', 'POR', 'pending', NULL, NULL, true),
  ('Romagnoli', 'DIF', 'pending', NULL, NULL, true),
  ('Patric', 'DIF', 'pending', NULL, NULL, true),
  ('Pellegrini Lu.', 'DIF', 'pending', NULL, NULL, true),
  ('Cataldi', 'CENTRO', 'pending', NULL, NULL, true),
  ('Przyborek', 'CENTRO', 'pending', NULL, NULL, true),
  ('Ratkov', 'ATT', 'pending', NULL, NULL, true),
  ('Fruchtl', 'POR', 'pending', NULL, NULL, true),
  ('Samooja', 'POR', 'pending', NULL, NULL, true),
  ('Jean', 'DIF', 'pending', NULL, NULL, true),
  ('Perez M.', 'DIF', 'pending', NULL, NULL, true),
  ('Fofana Sa.', 'CENTRO', 'pending', NULL, NULL, true),
  ('Berisha M.', 'CENTRO', 'pending', NULL, NULL, true),
  ('Gandelman', 'CENTRO', 'pending', NULL, NULL, true),
  ('Terracciano', 'POR', 'pending', NULL, NULL, true),
  ('Torriani', 'POR', 'pending', NULL, NULL, true),
  ('Tomori', 'DIF', 'pending', NULL, NULL, true),
  ('Diawara S.', 'DIF', 'pending', NULL, NULL, true),
  ('Athekame', 'DIF', 'pending', NULL, NULL, true),
  ('Fofana Y.', 'CENTRO', 'pending', NULL, NULL, true),
  ('Leao', 'ATT', 'pending', NULL, NULL, true),
  ('Nkunku', 'ATT', 'pending', NULL, NULL, true),
  ('Camarda', 'ATT', 'pending', NULL, NULL, true),
  ('Gimenez', 'ATT', 'pending', NULL, NULL, true),
  ('Strajnar', 'POR', 'pending', NULL, NULL, true),
  ('Antov', 'DIF', 'pending', NULL, NULL, true),
  ('Ciurria', 'CENTRO', 'pending', NULL, NULL, true),
  ('Pessina', 'CENTRO', 'pending', NULL, NULL, true),
  ('Petagna', 'ATT', 'pending', NULL, NULL, true),
  ('Contini', 'POR', 'pending', NULL, NULL, true),
  ('Beukema', 'DIF', 'pending', NULL, NULL, true),
  ('Buongiorno', 'DIF', 'pending', NULL, NULL, true),
  ('Marianucci', 'DIF', 'pending', NULL, NULL, true),
  ('Gutierrez', 'DIF', 'pending', NULL, NULL, true),
  ('Mazzocchi', 'DIF', 'pending', NULL, NULL, true),
  ('Giovane', 'ATT', 'pending', NULL, NULL, true),
  ('Lukaku', 'ATT', 'pending', NULL, NULL, true),
  ('Daffara', 'POR', 'pending', NULL, NULL, true),
  ('Suzuki', 'POR', 'pending', NULL, NULL, true),
  ('Circati', 'DIF', 'pending', NULL, NULL, true),
  ('Carboni F.', 'DIF', 'pending', NULL, NULL, true),
  ('Nicolussi Caviglia', 'CENTRO', 'pending', NULL, NULL, true),
  ('Sorensen O.', 'CENTRO', 'pending', NULL, NULL, true),
  ('Ondrejka', 'CENTRO', 'pending', NULL, NULL, true),
  ('De Marzi', 'POR', 'pending', NULL, NULL, true),
  ('Gollini', 'POR', 'pending', NULL, NULL, true),
  ('Ziolkowski', 'DIF', 'pending', NULL, NULL, true),
  ('Angelino', 'DIF', 'pending', NULL, NULL, true),
  ('Vaz', 'ATT', 'pending', NULL, NULL, true),
  ('Russo A.', 'POR', 'pending', NULL, NULL, true),
  ('Turati', 'POR', 'pending', NULL, NULL, true),
  ('Walukiewicz', 'DIF', 'pending', NULL, NULL, true),
  ('Candè', 'DIF', 'pending', NULL, NULL, true),
  ('Missori', 'DIF', 'pending', NULL, NULL, true),
  ('Pieragnolo', 'DIF', 'pending', NULL, NULL, true),
  ('Boloca', 'CENTRO', 'pending', NULL, NULL, true),
  ('Iannoni', 'CENTRO', 'pending', NULL, NULL, true),
  ('Konè I.', 'CENTRO', 'pending', NULL, NULL, true),
  ('Moro L.', 'ATT', 'pending', NULL, NULL, true),
  ('Paleari', 'POR', 'pending', NULL, NULL, true),
  ('Siviero', 'POR', 'pending', NULL, NULL, true),
  ('Biraghi', 'DIF', 'pending', NULL, NULL, true),
  ('Anjorin', 'CENTRO', 'pending', NULL, NULL, true),
  ('Zapata D.', 'ATT', 'pending', NULL, NULL, true),
  ('Padelli', 'POR', 'pending', NULL, NULL, true),
  ('Piana', 'POR', 'pending', NULL, NULL, true),
  ('Mlacic', 'DIF', 'pending', NULL, NULL, true),
  ('Arizala', 'DIF', 'pending', NULL, NULL, true),
  ('Camara A.', 'CENTRO', 'pending', NULL, NULL, true),
  ('Buksa', 'ATT', 'pending', NULL, NULL, true),
  ('Grandi', 'POR', 'pending', NULL, NULL, true),
  ('Pozzi', 'POR', 'pending', NULL, NULL, true),
  ('Sverko', 'DIF', 'pending', NULL, NULL, true),
  ('Gomes', 'DIF', 'pending', NULL, NULL, true),
  ('Bjarkason', 'CENTRO', 'pending', NULL, NULL, true),
  ('Duncan', 'CENTRO', 'pending', NULL, NULL, true),
  ('Lisman', 'ATT', 'pending', NULL, NULL, true),
  ('Adorante', 'ATT', 'pending', NULL, NULL, true),
  ('Vismara', 'POR', 'pending', NULL, NULL, true),
  ('Satalino', 'POR', 'pending', NULL, NULL, true),
  ('Pellegrini Lo.', 'CENTRO', 'pending', NULL, NULL, true),
  ('Aurelio', 'DIF', 'pending', NULL, NULL, true),
  ('Grillitsch', 'CENTRO', 'pending', NULL, NULL, true),
  ('Penev', 'POR', 'pending', NULL, NULL, true),
  ('Spence', 'DIF', 'pending', NULL, NULL, true),
  ('Pisseri', 'POR', 'pending', NULL, NULL, true),
  ('Radunovic', 'POR', 'pending', NULL, NULL, true),
  ('Milik', 'ATT', 'pending', NULL, NULL, true),
  ('De Martis', 'ATT', 'pending', NULL, NULL, true),
  ('Montipò', 'POR', 'pending', NULL, NULL, true),
  ('Omar Fayed', 'DIF', 'pending', NULL, NULL, true),
  ('Bleve', 'POR', 'pending', NULL, NULL, true),
  ('Tourè I.', 'CENTRO', 'pending', NULL, NULL, true),
  ('Laerke', 'CENTRO', 'pending', NULL, NULL, true),
  ('Comotto', 'CENTRO', 'pending', NULL, NULL, true),
  ('Goglichidze', 'DIF', 'pending', NULL, NULL, true),
  ('Macchioni', 'DIF', 'pending', NULL, NULL, true),
  ('Terracciano F.', 'DIF', 'pending', NULL, NULL, true),
  ('Ciervo', 'CENTRO', 'pending', NULL, NULL, true),
  ('Grabara', 'POR', 'pending', NULL, NULL, true),
  ('Maye', 'DIF', 'pending', NULL, NULL, true),
  ('Tchato', 'DIF', 'pending', NULL, NULL, true),
  ('Kambwala', 'DIF', 'pending', NULL, NULL, true),
  ('Mrozek', 'POR', 'pending', NULL, NULL, true),
  ('Ngonge', 'ATT', 'pending', NULL, NULL, true),
  ('Dembelè A.', 'DIF', 'pending', NULL, NULL, true),
  ('Massolin', 'CENTRO', 'pending', NULL, NULL, true),
  ('Jovanovic', 'CENTRO', 'pending', NULL, NULL, true),
  ('Ghidotti', 'POR', 'pending', NULL, NULL, true),
  ('Robinho Junior', 'ATT', 'pending', NULL, NULL, true),
  ('Mbangula', 'CENTRO', 'pending', NULL, NULL, true),
  ('Drameh', 'DIF', 'pending', NULL, NULL, true),
  ('Nzola', 'ATT', 'pending', NULL, NULL, true),
  ('Pompei', 'POR', 'pending', NULL, NULL, true),
  ('Enem', 'ATT', 'pending', NULL, NULL, true),
  ('Leite', 'DIF', 'pending', NULL, NULL, true),
  ('Alaba', 'DIF', 'pending', NULL, NULL, true),
  ('Neto', 'POR', 'pending', NULL, NULL, true);

CREATE TEMP TABLE desired_roster (nome text PRIMARY KEY, ruolo text NOT NULL, squadra text NOT NULL, prezzo integer NOT NULL) ON COMMIT DROP;
INSERT INTO desired_roster(nome,ruolo,squadra,prezzo) VALUES
  ('Vicario', 'POR', 'Tricchetracht Frankfurt', 34),
  ('Palmisani', 'POR', 'Tricchetracht Frankfurt', 1),
  ('Neto', 'POR', 'Tricchetracht Frankfurt', 1),
  ('Dimarco', 'DIF', 'Tricchetracht Frankfurt', 81),
  ('Molina N.', 'DIF', 'Tricchetracht Frankfurt', 44),
  ('Kamara H.', 'DIF', 'Tricchetracht Frankfurt', 7),
  ('Kaiki', 'DIF', 'Tricchetracht Frankfurt', 5),
  ('Valeri', 'DIF', 'Tricchetracht Frankfurt', 3),
  ('Cinquegrano', 'DIF', 'Tricchetracht Frankfurt', 1),
  ('Mangas', 'DIF', 'Tricchetracht Frankfurt', 1),
  ('Oyono A.', 'DIF', 'Tricchetracht Frankfurt', 1),
  ('Calhanoglu', 'CENTRO', 'Tricchetracht Frankfurt', 55),
  ('Frattesi', 'CENTRO', 'Tricchetracht Frankfurt', 36),
  ('Rowe', 'CENTRO', 'Tricchetracht Frankfurt', 20),
  ('Gudmundsson A.', 'CENTRO', 'Tricchetracht Frankfurt', 16),
  ('Milla', 'CENTRO', 'Tricchetracht Frankfurt', 3),
  ('Zhegrova', 'CENTRO', 'Tricchetracht Frankfurt', 1),
  ('Volpato', 'CENTRO', 'Tricchetracht Frankfurt', 1),
  ('Gaetano', 'CENTRO', 'Tricchetracht Frankfurt', 1),
  ('Martinez L.', 'ATT', 'Tricchetracht Frankfurt', 122),
  ('Scamacca', 'ATT', 'Tricchetracht Frankfurt', 38),
  ('Yeboah J.', 'ATT', 'Tricchetracht Frankfurt', 20),
  ('Robinson J.', 'ATT', 'Tricchetracht Frankfurt', 1),
  ('Santos A.', 'ATT', 'Tricchetracht Frankfurt', 1),
  ('Elphege', 'ATT', 'Tricchetracht Frankfurt', 1),
  ('Maignan', 'POR', 'Sesto Asensio', 36),
  ('Butez', 'POR', 'Sesto Asensio', 35),
  ('Sportiello', 'POR', 'Sesto Asensio', 1),
  ('Bremer', 'DIF', 'Sesto Asensio', 43),
  ('Pavlovic', 'DIF', 'Sesto Asensio', 30),
  ('Lucumì', 'DIF', 'Sesto Asensio', 25),
  ('Scalvini', 'DIF', 'Sesto Asensio', 14),
  ('Comuzzo', 'DIF', 'Sesto Asensio', 10),
  ('Doig', 'DIF', 'Sesto Asensio', 4),
  ('Gatti', 'DIF', 'Sesto Asensio', 1),
  ('Alaba', 'DIF', 'Sesto Asensio', 1),
  ('Baturina', 'CENTRO', 'Sesto Asensio', 44),
  ('Modric', 'CENTRO', 'Sesto Asensio', 28),
  ('Mora', 'CENTRO', 'Sesto Asensio', 16),
  ('Adzic', 'CENTRO', 'Sesto Asensio', 13),
  ('Vergara', 'CENTRO', 'Sesto Asensio', 11),
  ('Cissè A.', 'CENTRO', 'Sesto Asensio', 11),
  ('Pellegrini Lo.', 'CENTRO', 'Sesto Asensio', 8),
  ('Koopmeiners', 'CENTRO', 'Sesto Asensio', 4),
  ('Douvikas', 'ATT', 'Sesto Asensio', 64),
  ('Castro S.', 'ATT', 'Sesto Asensio', 30),
  ('Laurientè', 'ATT', 'Sesto Asensio', 19),
  ('Raimondo', 'ATT', 'Sesto Asensio', 9),
  ('Camarda', 'ATT', 'Sesto Asensio', 7),
  ('Kulenovic', 'ATT', 'Sesto Asensio', 1),
  ('Meret', 'POR', 'Pesciculini', 49),
  ('Milinkovic-Savic V.', 'POR', 'Pesciculini', 35),
  ('De Gea', 'POR', 'Pesciculini', 14),
  ('Wesley', 'DIF', 'Pesciculini', 55),
  ('Mancini', 'DIF', 'Pesciculini', 42),
  ('Mina', 'DIF', 'Pesciculini', 21),
  ('Buongiorno', 'DIF', 'Pesciculini', 13),
  ('Bellanova', 'DIF', 'Pesciculini', 3),
  ('Carlos Augusto', 'DIF', 'Pesciculini', 2),
  ('Estupinan', 'DIF', 'Pesciculini', 2),
  ('Dembelè A.', 'DIF', 'Pesciculini', 1),
  ('Barella', 'CENTRO', 'Pesciculini', 54),
  ('Politano', 'CENTRO', 'Pesciculini', 18),
  ('De Roon', 'CENTRO', 'Pesciculini', 14),
  ('Isaksen', 'CENTRO', 'Pesciculini', 11),
  ('Stankovic A.', 'CENTRO', 'Pesciculini', 7),
  ('Njie', 'CENTRO', 'Pesciculini', 2),
  ('Zalewski', 'CENTRO', 'Pesciculini', 1),
  ('Nicolussi Caviglia', 'CENTRO', 'Pesciculini', 1),
  ('Kean', 'ATT', 'Pesciculini', 63),
  ('Diao', 'ATT', 'Pesciculini', 30),
  ('Krstovic', 'ATT', 'Pesciculini', 25),
  ('De Ketelaere', 'ATT', 'Pesciculini', 20),
  ('Lucca', 'ATT', 'Pesciculini', 12),
  ('Lontani', 'ATT', 'Pesciculini', 1),
  ('Carnesecchi', 'POR', 'Partizan Degrado', 33),
  ('Corvi', 'POR', 'Partizan Degrado', 15),
  ('Falcone', 'POR', 'Partizan Degrado', 7),
  ('Solet', 'DIF', 'Partizan Degrado', 32),
  ('Ramon', 'DIF', 'Partizan Degrado', 31),
  ('Valdepenas', 'DIF', 'Partizan Degrado', 21),
  ('Hermoso', 'DIF', 'Partizan Degrado', 20),
  ('Bernasconi', 'DIF', 'Partizan Degrado', 14),
  ('Tiago Gabriel', 'DIF', 'Partizan Degrado', 10),
  ('Vojvoda', 'DIF', 'Partizan Degrado', 8),
  ('Lulli', 'DIF', 'Partizan Degrado', 4),
  ('Da Cunha', 'CENTRO', 'Partizan Degrado', 30),
  ('Diouf', 'CENTRO', 'Partizan Degrado', 27),
  ('Jones C.', 'CENTRO', 'Partizan Degrado', 27),
  ('Ekkelenkamp', 'CENTRO', 'Partizan Degrado', 25),
  ('Baldanzi', 'CENTRO', 'Partizan Degrado', 17),
  ('Casadei', 'CENTRO', 'Partizan Degrado', 9),
  ('Romano', 'CENTRO', 'Partizan Degrado', 7),
  ('Cacciamani', 'CENTRO', 'Partizan Degrado', 3),
  ('Berardi', 'ATT', 'Partizan Degrado', 35),
  ('Yildiz', 'ATT', 'Partizan Degrado', 25),
  ('Colombo', 'ATT', 'Partizan Degrado', 20),
  ('Davis K.', 'ATT', 'Partizan Degrado', 19),
  ('Dovbyk', 'ATT', 'Partizan Degrado', 17),
  ('Kvernadze', 'ATT', 'Partizan Degrado', 13),
  ('Caprile', 'POR', 'AC Asparaghese', 20),
  ('Muric', 'POR', 'AC Asparaghese', 15),
  ('Thiam', 'POR', 'AC Asparaghese', 1),
  ('Kalulu', 'DIF', 'AC Asparaghese', 42),
  ('Vasquez', 'DIF', 'AC Asparaghese', 16),
  ('Valle', 'DIF', 'AC Asparaghese', 15),
  ('Gabbia', 'DIF', 'AC Asparaghese', 6),
  ('Badiashile', 'DIF', 'AC Asparaghese', 5),
  ('Doekhi', 'DIF', 'AC Asparaghese', 4),
  ('Kofler', 'DIF', 'AC Asparaghese', 1),
  ('Dodò', 'DIF', 'AC Asparaghese', 1),
  ('Pulisic', 'CENTRO', 'AC Asparaghese', 43),
  ('Konè M.', 'CENTRO', 'AC Asparaghese', 31),
  ('Sucic P.', 'CENTRO', 'AC Asparaghese', 27),
  ('Kessiè', 'CENTRO', 'AC Asparaghese', 24),
  ('Atta', 'CENTRO', 'AC Asparaghese', 23),
  ('Mastantuono', 'CENTRO', 'AC Asparaghese', 20),
  ('Alajbegovic', 'CENTRO', 'AC Asparaghese', 12),
  ('Bernardeschi', 'CENTRO', 'AC Asparaghese', 5),
  ('Malen', 'ATT', 'AC Asparaghese', 151),
  ('Soulè', 'ATT', 'AC Asparaghese', 26),
  ('Gueye', 'ATT', 'AC Asparaghese', 4),
  ('Robinho Junior', 'ATT', 'AC Asparaghese', 1),
  ('Romero D.', 'ATT', 'AC Asparaghese', 1),
  ('Varela G.', 'ATT', 'AC Asparaghese', 1),
  ('Svilar', 'POR', 'San Gria', 63),
  ('De Marzi', 'POR', 'San Gria', 1),
  ('Gollini', 'POR', 'San Gria', 1),
  ('Bastoni', 'DIF', 'San Gria', 50),
  ('Tavares N.', 'DIF', 'San Gria', 32),
  ('Gila', 'DIF', 'San Gria', 27),
  ('Bracaglia', 'DIF', 'San Gria', 3),
  ('Pellegrini Lu.', 'DIF', 'San Gria', 2),
  ('Leysen F.', 'DIF', 'San Gria', 1),
  ('Mitaj', 'DIF', 'San Gria', 1),
  ('Viery', 'DIF', 'San Gria', 1),
  ('Conceicao', 'CENTRO', 'San Gria', 46),
  ('Rabiot', 'CENTRO', 'San Gria', 45),
  ('Saelemaekers', 'CENTRO', 'San Gria', 37),
  ('Chukwueze', 'CENTRO', 'San Gria', 20),
  ('Zaniolo', 'CENTRO', 'San Gria', 20),
  ('Cristante', 'CENTRO', 'San Gria', 8),
  ('Frendrup', 'CENTRO', 'San Gria', 6),
  ('Perrone', 'CENTRO', 'San Gria', 5),
  ('Kolo Muani', 'ATT', 'San Gria', 100),
  ('Beto', 'ATT', 'San Gria', 20),
  ('Gnonto', 'ATT', 'San Gria', 5),
  ('Osmajic', 'ATT', 'San Gria', 1),
  ('Lauberbach', 'ATT', 'San Gria', 1),
  ('Ngonge', 'ATT', 'San Gria', 1),
  ('Okoye', 'POR', 'Atl. Improvvisato', 15),
  ('Mrozek', 'POR', 'Atl. Improvvisato', 9),
  ('Motta', 'POR', 'Atl. Improvvisato', 1),
  ('Bisseck', 'DIF', 'Atl. Improvvisato', 42),
  ('Spinazzola', 'DIF', 'Atl. Improvvisato', 20),
  ('Bella-Kotchap', 'DIF', 'Atl. Improvvisato', 17),
  ('Cambiaso', 'DIF', 'Atl. Improvvisato', 15),
  ('Zè Pedro', 'DIF', 'Atl. Improvvisato', 9),
  ('Obrador', 'DIF', 'Atl. Improvvisato', 8),
  ('Pavard', 'DIF', 'Atl. Improvvisato', 5),
  ('Gallo', 'DIF', 'Atl. Improvvisato', 4),
  ('Zielinski', 'CENTRO', 'Atl. Improvvisato', 37),
  ('Locatelli', 'CENTRO', 'Atl. Improvvisato', 29),
  ('Jashari', 'CENTRO', 'Atl. Improvvisato', 18),
  ('Bernabè', 'CENTRO', 'Atl. Improvvisato', 17),
  ('Zambo Anguissa', 'CENTRO', 'Atl. Improvvisato', 17),
  ('Cancellieri', 'CENTRO', 'Atl. Improvvisato', 6),
  ('Konè I.', 'CENTRO', 'Atl. Improvvisato', 3),
  ('Pasalic', 'CENTRO', 'Atl. Improvvisato', 3),
  ('Esposito F.P.', 'ATT', 'Atl. Improvvisato', 72),
  ('Woltemade', 'ATT', 'Atl. Improvvisato', 45),
  ('Maldini', 'ATT', 'Atl. Improvvisato', 22),
  ('Bonny', 'ATT', 'Atl. Improvvisato', 21),
  ('Lang', 'ATT', 'Atl. Improvvisato', 20),
  ('Tourè E.', 'ATT', 'Atl. Improvvisato', 19),
  ('Skorupski', 'POR', 'Shark', 22),
  ('Stankovic F.', 'POR', 'Shark', 20),
  ('Montipò', 'POR', 'Shark', 12),
  ('Akanji', 'DIF', 'Shark', 50),
  ('Rrahmani', 'DIF', 'Shark', 36),
  ('Stones', 'DIF', 'Shark', 34),
  ('Chalobah T.', 'DIF', 'Shark', 32),
  ('Spence', 'DIF', 'Shark', 25),
  ('Ostigard', 'DIF', 'Shark', 25),
  ('Correia T.', 'DIF', 'Shark', 3),
  ('Troilo', 'DIF', 'Shark', 1),
  ('Orsolini', 'CENTRO', 'Shark', 34),
  ('Lobotka', 'CENTRO', 'Shark', 19),
  ('Loftus-Cheek', 'CENTRO', 'Shark', 15),
  ('Taylor K.', 'CENTRO', 'Shark', 10),
  ('Keita M.', 'CENTRO', 'Shark', 10),
  ('Karlstrom', 'CENTRO', 'Shark', 7),
  ('Musah', 'CENTRO', 'Shark', 6),
  ('Maleh', 'CENTRO', 'Shark', 1),
  ('Piccoli', 'ATT', 'Shark', 35),
  ('Neres', 'ATT', 'Shark', 29),
  ('Esposito Se.', 'ATT', 'Shark', 29),
  ('Pellegrino M.', 'ATT', 'Shark', 19),
  ('Nzola', 'ATT', 'Shark', 13),
  ('Cutrone', 'ATT', 'Shark', 13),
  ('Mandas', 'POR', 'AS Pipperia', 23),
  ('Bijlow', 'POR', 'AS Pipperia', 10),
  ('Perri', 'POR', 'AS Pipperia', 2),
  ('Di Lorenzo', 'DIF', 'AS Pipperia', 40),
  ('Couto', 'DIF', 'AS Pipperia', 21),
  ('Kristensen T.', 'DIF', 'AS Pipperia', 11),
  ('Delprato', 'DIF', 'AS Pipperia', 3),
  ('Jimenez A.', 'DIF', 'AS Pipperia', 2),
  ('Hainaut', 'DIF', 'AS Pipperia', 1),
  ('Birindelli', 'DIF', 'AS Pipperia', 1),
  ('Balerdi', 'DIF', 'AS Pipperia', 1),
  ('Paz N.', 'CENTRO', 'AS Pipperia', 41),
  ('Samardzic', 'CENTRO', 'AS Pipperia', 27),
  ('Zaccagni', 'CENTRO', 'AS Pipperia', 26),
  ('McKennie', 'CENTRO', 'AS Pipperia', 13),
  ('Pisilli', 'CENTRO', 'AS Pipperia', 7),
  ('Goncalves P.', 'CENTRO', 'AS Pipperia', 1),
  ('Moreira', 'CENTRO', 'AS Pipperia', 1),
  ('Colpani', 'CENTRO', 'AS Pipperia', 1),
  ('Ramos G.', 'ATT', 'AS Pipperia', 76),
  ('Hojlund', 'ATT', 'AS Pipperia', 76),
  ('Pinamonti', 'ATT', 'AS Pipperia', 40),
  ('Simeone', 'ATT', 'AS Pipperia', 30),
  ('Adams A.', 'ATT', 'AS Pipperia', 9),
  ('Geubbels', 'ATT', 'AS Pipperia', 1),
  ('Martinez Jo.', 'POR', 'FC Internazioanale', 59),
  ('Provedel', 'POR', 'FC Internazioanale', 24),
  ('Di Gennaro', 'POR', 'FC Internazioanale', 1),
  ('N''Dicka', 'DIF', 'FC Internazioanale', 30),
  ('Miranda J.', 'DIF', 'FC Internazioanale', 24),
  ('Celik', 'DIF', 'FC Internazioanale', 12),
  ('Haps', 'DIF', 'FC Internazioanale', 8),
  ('Fortini', 'DIF', 'FC Internazioanale', 6),
  ('Theate', 'DIF', 'FC Internazioanale', 2),
  ('Belghali', 'DIF', 'FC Internazioanale', 1),
  ('Provstgaard', 'DIF', 'FC Internazioanale', 1),
  ('McTominay', 'CENTRO', 'FC Internazioanale', 46),
  ('De Bruyne', 'CENTRO', 'FC Internazioanale', 28),
  ('Ederson D.S.', 'CENTRO', 'FC Internazioanale', 21),
  ('Vlasic', 'CENTRO', 'FC Internazioanale', 16),
  ('Fazzini', 'CENTRO', 'FC Internazioanale', 3),
  ('Thorstvedt', 'CENTRO', 'FC Internazioanale', 3),
  ('Ndour', 'CENTRO', 'FC Internazioanale', 1),
  ('Mandragora', 'CENTRO', 'FC Internazioanale', 1),
  ('Thuram', 'ATT', 'FC Internazioanale', 92),
  ('Dybala', 'ATT', 'FC Internazioanale', 50),
  ('Raspadori', 'ATT', 'FC Internazioanale', 32),
  ('Mendy P.', 'ATT', 'FC Internazioanale', 16),
  ('Adams C.', 'ATT', 'FC Internazioanale', 13),
  ('Noslin', 'ATT', 'FC Internazioanale', 1);

DO $$
DECLARE v_missing text;
BEGIN
  SELECT string_agg(d.nome, ', ' ORDER BY d.nome) INTO v_missing FROM desired_roster d LEFT JOIN public.players p ON p.nome=d.nome WHERE p.id IS NULL;
  IF v_missing IS NOT NULL THEN RAISE EXCEPTION 'Giocatori rosa mancanti nel listone: %', v_missing; END IF;
END $$;

UPDATE public.players p SET ruolo=d.ruolo, stato='sold', vincitore=d.squadra, prezzo_finale=d.prezzo, in_serie_a=true FROM desired_roster d WHERE p.nome=d.nome;

UPDATE public.squadre s SET crediti=v.crediti FROM (VALUES
  ('Tricchetracht Frankfurt', 5),
  ('Sesto Asensio', 10),
  ('Pesciculini', 4),
  ('Partizan Degrado', 31),
  ('AC Asparaghese', 5),
  ('San Gria', 3),
  ('Atl. Improvvisato', 26),
  ('Shark', 0),
  ('AS Pipperia', 14),
  ('FC Internazioanale', 0)
) AS v(nome,crediti) WHERE s.nome=v.nome;

DO $$
DECLARE v_bad text; v_sold integer; v_total integer;
BEGIN
  SELECT count(*) INTO v_total FROM public.players;
  IF v_total <> 599 THEN RAISE EXCEPTION 'ERRORE: players totali %, attesi 599', v_total; END IF;
  SELECT count(*) INTO v_sold FROM public.players WHERE stato='sold';
  IF v_sold <> 250 THEN RAISE EXCEPTION 'ERRORE: sold %, attesi 250', v_sold; END IF;
  SELECT string_agg(z.vincitore || ' (' || z.tot || '/' || z.por || '/' || z.dif || '/' || z.cen || '/' || z.att || ')', '; ') INTO v_bad
  FROM (SELECT vincitore, count(*) tot, count(*) FILTER (WHERE ruolo='POR') por, count(*) FILTER (WHERE ruolo='DIF') dif, count(*) FILTER (WHERE ruolo='CENTRO') cen, count(*) FILTER (WHERE ruolo='ATT') att FROM public.players WHERE stato='sold' GROUP BY vincitore) z
  WHERE z.tot<>25 OR z.por<>3 OR z.dif<>8 OR z.cen<>8 OR z.att<>6;
  IF v_bad IS NOT NULL THEN RAISE EXCEPTION 'Rose non valide: %', v_bad; END IF;
  IF (SELECT count(DISTINCT vincitore) FROM public.players WHERE stato='sold') <> 10 THEN RAISE EXCEPTION 'ERRORE: non risultano 10 squadre con giocatori sold'; END IF;
END $$;

INSERT INTO public.snapshot_players(player_id,stato,vincitore,prezzo_finale) SELECT id,stato,vincitore,prezzo_finale FROM public.players;
INSERT INTO public.snapshot_squadre(squadra_id,crediti) SELECT id,crediti FROM public.squadre;

COMMIT;

-- CONTROLLO FINALE DA ESEGUIRE DOPO IL COMMIT:
SELECT vincitore, count(*) AS tot, count(*) FILTER (WHERE ruolo='POR') AS por, count(*) FILTER (WHERE ruolo='DIF') AS dif, count(*) FILTER (WHERE ruolo='CENTRO') AS centro, count(*) FILTER (WHERE ruolo='ATT') AS att FROM public.players WHERE stato='sold' GROUP BY vincitore ORDER BY vincitore;
SELECT nome, crediti FROM public.squadre ORDER BY id;
SELECT stato, count(*) FROM public.players GROUP BY stato ORDER BY stato;
